---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: graphql
spec:
  template:
    spec:
      containers:
        - name: graphql
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GRAPHQL_DEFAULT_CACHE_TTL
              value: "0"
            - name: APP_GRAPHQL_FOLDER_CACHE_TTL
              value: "0"
            - name: APP_GRAPHQL_BOOKS_CACHE_TTL
              value: "0"
          #   - name: APP_NATS_HOSTNAME
          #     value: nats.nats
          #   - name: APP_RETHINKDB_HOSTNAME
          #     value: rethinkdb.rethinkdb
          args:
            - --hot
            - services/graphql-gateway.service.js
          volumeMounts:
            - name: nfs-shared
              mountPath: /usr/app/assets/data/archives/weekly
            # - name: nfs-zarya
            #   mountPath: /usr/app/assets/data/archives/comics
      volumes:
        - name: nfs-shared
          nfs:
            server: nfs-shared.nfs-shared.svc.cluster.local
            path: /weekly
        # - name: nfs-zarya
        #   nfs:
        #     server: nfs-wd-zarya.nfs-wd-zarya.svc.cluster.local
        #     path: /comics
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api
                  - archives
                  - books
                  - graphql
                  - pages
              topologyKey: kubernetes.io/hostname
