---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: graphql
spec:
  template:
    spec:
      containers:
        - name: graphql
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GRAPHQL_ONE_MINUTE_CACHE_TTL
              value: "5"
            - name: APP_GRAPHQL_ONE_DAY_CACHE_TTL
              value: "10"
            - name: APP_GRAPHQL_ONE_YEAR_CACHE_TTL
              value: "20"
            # - name: APP_RETHINKDB_HOSTNAME
            #   value: rethinkdb.rethinkdb
          args:
            - --hot
            - services/graphql-gateway.service.js
          volumeMounts:
            - name: nfs-shared
              mountPath: /usr/app/assets/data/archives/weekly
            # - name: nfs-zarya
            #   mountPath: /usr/app/assets/data/archives/comics
      volumes:
        - name: nfs-shared
          nfs:
            server: nfs-shared.nfs-shared.svc.cluster.local
            path: /weekly
            readOnly: true
        # - name: nfs-zarya
        #   nfs:
        #     server: nfs-wd-zarya.nfs-wd-zarya.svc.cluster.local
        #     path: /comics
        #     readOnly: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api
                  - archives
                  - books
                  - graphql
                  - pages
              topologyKey: kubernetes.io/hostname
