---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apollo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    flame.pawelmalak/name: ouistity-apollo
    flame.pawelmalak/url: https://apollo.ouistity.shokohsc.home
    flame.pawelmalak/type: app
    flame.pawelmalak/icon: wrench
spec:
  rules:
  - host: apollo.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: graphql
            port:
              number: 7000
  tls:
  - hosts:
    - apollo.ouistity.shokohsc.home
    secretName: apollo-cert
