apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: ouistity
build:
  artifacts:
  - image: shokohsc/moleculer-ouistity
    context: .
    sync:
      manual:
      - src: services/**/*.js
        dest: .
      - src: mixins/*.js
        dest: .
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: shokohsc/moleculer-ouistity
      sync:
        manual:
        - src: services/**/*.js
          dest: .
        - src: mixins/*.js
          dest: .
- name: shokohsc
  build:
    artifacts:
    - image: shokohsc/moleculer-ouistity
      sync:
        manual:
        - src: services/**/*.js
          dest: .
        - src: mixins/*.js
          dest: .
      kaniko:
        cache:
          repo: shokohsc/moleculer-ouistity
    cluster:
      dockerConfig:
        secretName: kaniko-secret
      namespace: kaniko
      pullSecretName: kaniko-secret
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
  deploy:
    kustomize:
      paths:
      - k8s/overlays/shokohsc
- name: prod
  build:
    artifacts:
    - image: shokohsc/moleculer-ouistity
      kaniko:
        cache:
          repo: shokohsc/moleculer-ouistity
        dockerfile: Dockerfile
    cluster:
      dockerConfig:
        secretName: kaniko-secret
      namespace: kaniko
      pullSecretName: kaniko-secret
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
