---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pages
spec:
  template:
    spec:
      containers:
        - name: pages
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: https://api.ouistity.shokohsc.home
            # - name: APP_RETHINKDB_HOSTNAME
            #   value: rethinkdb.rethinkdb
          args:
            - --hot
            - services/pages.service.js
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api
                  - archives
                  - books
                  - graphql
                  - pages
              topologyKey: kubernetes.io/hostname
