---
apiVersion: v1
kind: Service
metadata:
  name: pages
  labels:
    app: pages
spec:
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: pages
