---
apiVersion: v1
kind: Service
metadata:
  name: archives
  labels:
    app: archives
spec:
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: archives
