---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: marvel
spec:
  selector:
    matchLabels:
      app: marvel
  template:
    metadata:
      labels:
        app: marvel
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "5050"
    spec:
      containers:
        - name: marvel
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: http://api.svc.cluster.local
            - name: APP_NATS_HOSTNAME
              value: nats
            - name: APP_REDIS_HOSTNAME
              value: redis
          args:
            - services/marvel/*.service.js
          ports:
            - name: metrics
              containerPort: 5050
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: metrics
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              port: metrics
              path: /metrics
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 100m
              memory: 64M
