---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: books
spec:
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: /api/v1/books/metrics
      #   prometheus.io/port: "5050"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: books
          image: shokohsc/moleculer-ouistity
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: http://api.svc.cluster.local
            - name: APP_RETHINKDB_HOSTNAME
              value: rethinkdb
            - name: APP_NATS_HOSTNAME
              value: nats
            - name: APP_RABBITMQ_HOSTNAME
              value: rabbitmq
            - name: APP_RABBITMQ_USERNAME
              value: rabbitmq
            - name: APP_RABBITMQ_PASSWORD
              value: changeme
            - name: APP_REDIS_HOSTNAME
              value: redis
          args:
            - services/books.service.js
          # ports:
          #   - name: http
          #     containerPort: 5000
          #     protocol: TCP
          #   - name: metrics
          #     containerPort: 5050
          #     protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     port: http
          #     path: /
          # readinessProbe:
          #   httpGet:
          #     port: http
          #     path: /
