---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rethinkdb
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    flame.pawelmalak/name: ouistity-rethinkdb
    flame.pawelmalak/url: https://rethinkdb.ouistity.shokohsc.home
    flame.pawelmalak/type: app
    flame.pawelmalak/icon: wrench
spec:
  rules:
  - host: rethinkdb.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rethinkdb
            port:
              number: 8080
  tls:
  - hosts:
    - rethinkdb.ouistity.shokohsc.home
    secretName: rethinkdb-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    flame.pawelmalak/name: ouistity-rabbitmq
    flame.pawelmalak/url: https://rabbitmq.ouistity.shokohsc.home
    flame.pawelmalak/type: app
    flame.pawelmalak/icon: wrench
spec:
  rules:
  - host: rabbitmq.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
  tls:
  - hosts:
    - rabbitmq.ouistity.shokohsc.home
    secretName: rabbitmq-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-commander
  annotations:
    kubernetes.io/ingress.class: nginx
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    flame.pawelmalak/name: ouistity-redis
    flame.pawelmalak/url: https://redis.ouistity.shokohsc.home
    flame.pawelmalak/type: app
    flame.pawelmalak/icon: wrench
spec:
  rules:
  - host: redis.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redis-commander
            port:
              number: 80
  tls:
  - hosts:
    - redis.ouistity.shokohsc.home
    secretName: redis-commander-cert
